### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by andresousa** [scannieapp/scannie-ios#3]

**Comment by andresousa** [comment]
- [ ] Create new folder [#8](https://github.com/scannieapp/scannie-ios/issues/8)
- [ ] Display folders [#9](https://github.com/scannieapp/scannie-ios/issues/9)
- [ ] Add file to folder [#10](https://github.com/scannieapp/scannie-ios/issues/10)
- [ ] Rename folder [#11](https://github.com/scannieapp/scannie-ios/issues/11)
